### ISSUE TITLE
Cache user name / key ID mappings, use to list recipients

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/ironssh#14]
As you add recipients to files, maintain a cache of "login@hostname":keyID mappings. Just use a text file in the .ssh directory.

Use this list to build a utility that will list the recipients of a given .iron file, and add functionality to download that will list the recipients of a file that is downloaded.

**Comment by zmre** [comment]
With this, I'd like to see a few things: 
1. Some kind of `listrcpts` command
2. Some kind of `resetrcpts` or `clearrcpts` command
3. On upload, display who the recipients are if there are any.

Don't count self since you can't remove yourself anyway.

**Comment by zmre** [comment]
Consider also a `lookuprcpt` command that would check to see if a username has a public key listed and if it does, add to the local key cache.

**Comment by BobWall23** [comment]
Resolved by PR #35
