### ISSUE TITLE
Public key should be uploaded if it doesn't exist on connect

### ISSUE THREAD

**Issue by zmre** [IronCoreLabs/ironssh#16]
If someone is using `ironsftp` on multiple machines, the only machine that will get the pubkey uploaded is the one that they're connected to when their GPG key is generated. Instead, on login to any machine, the pubkey file should be checked for an iron key and if it doesn't exist or isn't the same as the user's local public gpg key, it should get installed in place.

**Comment by BobWall23** [comment]
Closed by PR #34
