### ISSUE TITLE
Should not prompt for passphrase if id_rsa not encrypted

### ISSUE THREAD

**Issue by zmre** [IronCoreLabs/ironssh#19]
With an unencrypted private key, I still get a prompt for a password:

```
Enter passphrase for SSH key file:
```

**Comment by BobWall23** [comment]
I did that originally, but I figured people probably really wouldn't be using unprotected keys. No problem to put the code back to try with no passphrase first.

**Comment by zmre** [comment]
It will make my scripts for generating keys and wrangling them work better...

**Comment by BobWall23** [comment]
Ah - true

**Comment by BobWall23** [comment]
Fixed in PR #20
